### ISSUE TITLE
[Bug]: PkHex (.NET 8, Windows x64 build) crashes with System.EntryPointNotFoundException

### ISSUE THREAD

**Issue by voltagex** [Whisky-App/Whisky#1069]
### Description

PkHex crashes, but it does look like the program starts running as it's able to write to the log.

![image](https://github.com/user-attachments/assets/ec5f6891-c039-4154-b878-076d5e06d79f)

### Steps to reproduce

git clone https://github.com/kwsch/PKHeX
build on Windows with `dotnet publish -p:PublishSingleFile=true -r win-x64 .\PKHeX.WinForms\PKHeX.WinForms.csproj`

Download and install https://download.visualstudio.microsoft.com/download/pr/3980ab0a-379f-44a0-9be6-eaf74c07a3b3/bd1cc6107ff3d8fe0104d30f01339b74/dotnet-runtime-8.0.7-win-x64.exe in a new bottle.

Copy the built exe to your mac and attempt to run it

### Expected behaviour

PkHex runs... maybe

### Logs

```bash
The following error is written to the log


System.EntryPointNotFoundException: Unable to find an entry point named 'GetThreadDpiHostingBehavior' in DLL 'USER32.dll'.
   at System.Windows.Forms.DpiHelper.DpiAwarenessScope..ctor(DPI_AWARENESS_CONTEXT context, DPI_HOSTING_BEHAVIOR behavior)
   at System.Windows.Forms.DpiHelper.EnterDpiAwarenessScope(DPI_AWARENESS_CONTEXT awareness, DPI_HOSTING_BEHAVIOR dpiHosting)
   at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Application.ThreadContext.get_MarshalingControl()
   at System.Windows.Forms.WindowsFormsSynchronizationContext..ctor()
   at System.Windows.Forms.WindowsFormsSynchronizationContext.InstallIfNeeded()
   at System.Windows.Forms.Control..ctor(Boolean autoInstallSyncContext)
   at System.Windows.Forms.ScrollableControl..ctor()
   at System.Windows.Forms.ContainerControl..ctor()
   at System.Windows.Forms.Form..ctor()
   at PKHeX.WinForms.Program.Main()
System.ArgumentException: The NeutralResourcesLanguageAttribute on the assembly "PKHeX, Version=24.7.27.0, Culture=neutral, PublicKeyToken=null" specifies an invalid culture name: "en".
 ---> System.Globalization.CultureNotFoundException: Culture is not supported. (Parameter 'name')
en is an invalid culture identifier.
   at System.Globalization.CultureInfo.GetCultureInfo(String name)
   at System.Resources.ManifestBasedResourceGroveler.GetNeutralResourcesLanguage(Assembly a, UltimateResourceFallbackLocation& fallbackLocation)
   --- End of inner exception stack trace ---
   at System.Resources.ManifestBasedResourceGroveler.GetNeutralResourcesLanguage(Assembly a, UltimateResourceFallbackLocation& fallbackLocation)
   at System.Resources.ResourceManager.CommonAssemblyInit()
   at PKHeX.WinForms.Properties.Resources.get_ResourceManager()
   at PKHeX.WinForms.Properties.Resources.get_Icon()
   at PKHeX.WinForms.ErrorWindow.InitializeComponent()
   at PKHeX.WinForms.ErrorWindow.ShowErrorDialog(String friendlyMessage, Exception ex, Boolean allowContinue)
   at PKHeX.WinForms.Program.CurrentDomain_UnhandledException(Object sender, UnhandledExceptionEventArgs e)
```
```


### What version of Whisky are you using?

2.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by voltagex** [comment]
https://github.com/FRACerqueira/PromptPlus/issues/125 is one of the only other instances of this I can find.

**Comment by voltagex** [comment]
The other error can only be fixed with Wine 9 apparently... https://forum.winehq.org/viewtopic.php?t=38337

**Comment by KirovAir** [comment]
I'm having a similar culture issue with the CnCNet client which was not present in an older version of Whisky it seems. Not sure what could be the issue..
```
msync: bootstrapped mach port on wine-22b6d9c-msync.
msync: up and running.
0024:err:eventlog:ReportEventW L"Application: CnCNetYRLauncher.exe\nFramework Version: v4.0.30319\nDescription: The process was terminated due to an unhandled exception.\nException Info: System.TypeInitializationException\nStack:\n   at System.Globalization.CultureInfo.get_UserDefaultCulture()\n   at System.Threading.Thr"...

Unhandled Exception:
   Cannot print exception string because Exception.ToString() failed.
wine: Unhandled exception 0xe0434352 in thread 24 at address 000000007B0153CE (thread 0024), starting debugger...
0024:err:seh:start_debugger Couldn't start debugger L"winedbg --auto 32 336" (2)
Read the Wine Developers Guide on how to set up winedbg or another debugger
```

**Comment by TitanicMT** [comment]
Was this issue solved? I still encountered this issue with .Net 9 v9.0.3.
