### ISSUE TITLE
[Bug]: Doesn't remember imported bottles

### ISSUE THREAD

**Issue by tarasis** [Whisky-App/Whisky#385]
### Description

I exported a bottle from Whisky on macOS 14 beta partition I had. I have put macOS 14 RC on my main partition, installed Whisky and imported the bottle.

For the session it shows the bottle in the UI and everything works as it should.

After I quite, I reopen whisky and the bottle is missing from the UI

### Steps to reproduce

1) Open empty Whisky
2) Import bottle
3) Close Whisky
4) Reopen Whisky, bottle gone

### Expected behaviour

The Whisky would remember the imported bottle

### Logs

```bash
There are no logs because Wine wasn't actually used.

--

These are the logs from the imported bottle when I ran the game, don't think they are relevant.


Whisky Version: 1.3.1
Date: 14/09/2023, 15:38:12
macOS Version: Version 14.0 (Build 23A339)
Bottle Name: BG3Win
Wine Version: 7.7.0
Windows Version: win10
Bottle URL: /Users/tarasis/Games/Bottles/E0FC2751-050F-4FF7-8F1B-4BBF1EFF9732

Arguments: start /unix /Users/tarasis/Games/Bottles/E0FC2751-050F-4FF7-8F1B-4BBF1EFF9732/drive_c/GOG Games/Baldurs Gate 3/bin/bg3_dx11.exe 

Launched Wine (1573)
007c:err:module:open_builtin_so_file failed to load .so lib "/Users/tarasis/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/Wine/lib/wine/x86_64-unix/wineusb.sys.so"
007c:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
info:    OpenXR
[mvk-info] Created VkInstance for Vulkan version 1.1.0, as requested by app, with the following 3 Vulkan extensions enabled:
		VK_KHR_get_surface_capabilities2 v1
		VK_KHR_surface v25
		VK_EXT_metal_surface v1
info:  DXVK: v1.10.3-20230507-async (macOS)
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
rface v1
		VK_EXT_pipeline_creation_cache_control v3
		VK_EXT_post_depth_coverage v1
		VK_EXT_private_data v1
		VK_EXT_robustness2 v1
		VK_EXT_sample_locations v1
		VK_EXT_scalar_block_layout v1
		VK_EXT_separate_stencil_usage v1
		VK_EXT_shader_atomic_float v1
		VK_EXT_shader_stencil_export v1
		VK_EXT_shader_viewport_index_layer v1
		VK_EXT_subgroup_size_control v2
		VK_EXT_surface_maintenance1 v1
		VK_EXT_swapchain_colorspace v4
		VK_EXT_swapchain_maintenance1 v1
		VK_EXT_texel_buffer_alignment v1
		VK_EXT_texture_compression_astc_hdr v1
		VK_EXT_vertex_attribute_divisor v3
		VK_AMD_gpu_shader_half_float v2
		VK_AMD_negative_viewport_height v1
		VK_AMD_shader_image_load_store_lod v1
		VK_AMD_shader_trinary_minmax v1
		VK_IMG_format_pvrtc v1
		VK_INTEL_shader_integer_functions2 v1
		VK_GOOGLE_display_timing v1
		VK_MVK_macos_surface v3
		VK_MVK_moltenvk v37
		VK_NV_fragment_shader_barycentric v1
		VK_NV_glsl_shader v1
info:    Device name:     : Apple M1
info:    Driver version   : 0.2.2011
info:    VK_EXT_robustness2
info:    VK_KHR_timeline_semaphore
info:    robustBufferAccess                     : 1
info:    fullDrawIndexUint32                    : 1
info:    imageCubeArray                         : 1
info:    independentBlend                       : 1
info:    multiDrawIndirect                      : 1
info:    pipelineStatisticsQuery                : 0
info:    vertexPipelineStoresAndAtomics         : 0
info:    shaderCullDistance                     : 0
info:  VK_EXT_memory_priority
info:    memoryPriority                         : 0
info:    geometryStreams                        : 0
info:    Graphics : 0
info:    Transfer : 0
info:  Game: bg3_dx11.exe
info:    VK_KHR_surface
[mvk-info] Created VkInstance for Vulkan version 1.1.0, as requested by app, with the following 3 Vulkan extensions enabled:
		VK_KHR_get_surface_capabilities2 v1
		VK_KHR_surface v25
		VK_EXT_metal_surface v1
info:      Size: 16384 MiB
info:      Memory Type[3]: Property Flags = 0x11
info:    VK_KHR_get_surface_capabilities2
	VK_KHR_multiview v1
		VK_KHR_portability_subset v1
		VK_KHR_push_descriptor v2
		VK_KHR_relaxed_block_layout v1
		VK_KHR_sampler_mirror_clamp_to_edge v3
		VK_KHR_sampler_ycbcr_conversion v14
		VK_KHR_separate_depth_stencil_layouts v1
		VK_KHR_shader_draw_parameters v1
		VK_KHR_shader_float_controls v4
		VK_KHR_shader_float16_int8 v1
		VK_KHR_shader_subgroup_extended_types v1
		VK_KHR_spirv_1_4 v1
		VK_KHR_storage_buffer_storage_class v1
		VK_KHR_surface v25
		VK_KHR_swapchain v70
		VK_KHR_swapchain_mutable_format v1
		VK_KHR_timeline_semaphore v2
		VK_KHR_uniform_buffer_standard_layout v1
		VK_KHR_variable_pointers v1
		VK_EXT_buffer_device_address v2
		VK_EXT_debug_marker v4
		VK_EXT_debug_report v10
		VK_EXT_debug_utils v2
		VK_EXT_descriptor_indexing v2
		VK_EXT_external_memory_host v1
		VK_EXT_fragment_shader_interlock v1
		VK_EXT_hdr_metadata v2
		VK_EXT_host_query_reset v1
		VK_EXT_image_robustness v1
		VK_EXT_inline_uniform_block v1
		VK_EXT_memory_budget v1
		VK_EXT_metal_objects v1
		VK_EXT_metal_surface v1
		VK_EXT_pipeline_creation_cache_control v3
		VK_EXT_post_depth_coverage v1
		VK_EXT_private_data v1
		VK_EXT_robustness2 v1
		VK_EXT_sample_locations v1
		VK_EXT_scalar_block_layout v1
		VK_EXT_separate_stencil_usage v1
		VK_EXT_shader_atomic_float v1
		VK_EXT_shader_stencil_export v1
		VK_EXT_shader_viewport_index_layer v1
		VK_EXT_subgroup_size_control v2
		VK_EXT_surface_maintenance1 v1
		VK_EXT_swapchain_colorspace v4
		VK_EXT_swapchain_maintenance1 v1
		VK_EXT_texel_buffer_alignment v1
		VK_EXT_texture_compression_astc_hdr v1
		VK_EXT_vertex_attribute_divisor v3
		VK_AMD_gpu_shader_half_float v2
		VK_AMD_negative_viewport_height v1
		VK_AMD_shader_image_load_store_lod v1
		VK_AMD_shader_trinary_minmax v1
		VK_IMG_format_pvrtc v1
		VK_INTEL_shader_integer_functions2 v1
		VK_GOOGLE_display_timing v1
		VK_MVK_macos_surface v3
		VK_MVK_moltenvk v37
		VK_NV_fragment_shader_barycentric v1
		VK_NV_glsl_shader v1
info:      Flags: 0x1
info:    Format:       VK_FORMAT_A2B10G10R10_UNORM_PACK32
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  1440x900
info:  DXVK: v1.10.3-20230507-async (macOS)
info:    VK_KHR_win32_surface
info:    Driver: 0.2.2011
info:      Memory Type[0]: Property Flags = 0x1
info:      Memory Type[3]: Property Flags = 0x11
err:     fs  : FS_0fd66a4edfc1f5bf50181c12a4e49063dfdee5a6
info:    Exclusive FS: 1
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Fragment shader function could not be compiled into pipeline. See previous logged error.
err:   DxvkGraphicsPipeline: Failed to compile pipeline
err:     vs  : VS_8508ce441c51e4320b909f5f6f1d23e967304984
err:     fs  : FS_0e439cc11284ceac32437fa2c523a2aa1c3c4696
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Fragment shader function could not be compiled into pipeline. See previous logged error.
err:   DxvkGraphicsPipeline: Failed to compile pipeline
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Fragment shader function could not be compiled into pipeline. See previous logged error.
0218: thread_get_state failed on Apple Silicon - faking zero debug registers
info:    Exclusive FS: 1
[mvk-info] Created 3 swapchain images with initial size (1261, 762) and contents scale 1.0 for screen Built-in Retina Display.
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Fragment shader function could not be compiled into pipeline. See previous logged error.
err:   DxvkGraphicsPipeline: Failed to compile pipeline
err:     vs  : VS_6b2569b591272b62c3abcf87b1ce7363834c6c6f
err:     fs  : FS_1b41e44cb4eb18308cf379a82edd92f6e662aa18
err:     attr 0 : location 1, binding 0, format VK_FORMAT_R32G32B32_SFLOAT, offset 0
err:     attr 1 : location 5, binding 0, format VK_FORMAT_R16G16B16A16_SNORM, offset 12
err:     attr 2 : location 0, binding 0, format VK_FORMAT_R16G16_SFLOAT, offset 20
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Fragment shader function could not be compiled into pipeline. See previous logged error.
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Fragment shader function could not be compiled into pipeline. See previous logged error.
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Shader module does not contain an entry point named 'main0'.
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Fragment shader function could not be compiled into pipeline. See previous logged error.
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Fragment shader function could not be compiled into pipeline. See previous logged error.
err:     fs  : FS_6709e1ab591ad8c9e784f8816c1027206888685e
info:  DXVK: v1.10.3-20230507-async (macOS)
info:    OpenXR
[mvk-info] Created VkInstance for Vulkan version 1.1.0, as requested by app, with the following 3 Vulkan extensions enabled:
		VK_KHR_get_surface_capabilities2 v1
		VK_KHR_surface v25
		VK_EXT_metal_surface v1
info:      Memory Type[0]: Property Flags = 0x1
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Shader module does not contain an entry point named 'main0'.
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Fragment shader function could not be compiled into pipeline. See previous logged error.
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Shader module does not contain an entry point named 'main0'.
err:     attr 0 : location 3, binding 0, format VK_FORMAT_R32G32B32_SFLOAT, offset 0
err:     attr 2 : location 4, binding 0, format VK_FORMAT_R8G8B8A8_UNORM, offset 20
err:     binding 2 : binding 6, stride 16, rate 1, divisor 1
err:   DxvkGraphicsPipeline: Failed to compile pipeline
err:     vs  : VS_0691d7a878919cb51a41cf9c919684d927046824
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Fragment shader function could not be compiled into pipeline. See previous logged error.
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Fragment shader function could not be compiled into pipeline. See previous logged error.
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Shader module does not contain an entry point named 'main0'.
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Fragment shader function could not be compiled into pipeline. See previous logged error.
err:   DxvkGraphicsPipeline: Failed to compile pipeline
err:   DxvkGraphicsPipeline: Failed to compile pipeline
err:     vs  : VS_b3a78df1aff49f1edc7802a34a65c8c3ff8214f1
err:     fs  : FS_11085878e38b5fd3d0063f85611ac227e314dbaf
err:     attr 0 : location 0, binding 1, format VK_FORMAT_R32G32B32_SFLOAT, offset 0
err:     attr 1 : location 3, binding 1, format VK_FORMAT_R16G16B16A16_SNORM, offset 12
err:     attr 2 : location 2, binding 0, format VK_FORMAT_R8G8B8A8_UNORM, offset 0
err:     vs  : VS_b3a78df1aff49f1edc7802a34a65c8c3ff8214f1
err:     fs  : FS_11085878e38b5fd3d0063f85611ac227e314dbaf
err:     attr 0 : location 0, binding 1, format VK_FORMAT_R32G32B32_SFLOAT, offset 0
err:     attr 1 : location 3, binding 1, format VK_FORMAT_R16G16B16A16_SNORM, offset 12
err:     attr 2 : location 4, binding 0, format VK_FORMAT_R16G16_SFLOAT, offset 0
err:     attr 3 : location 2, binding 6, format VK_FORMAT_R32G32B32A32_SFLOAT, offset 0
err:     binding 0 : binding 0, stride 8, rate 0, divisor 0
err:     binding 1 : binding 1, stride 20, rate 0, divisor 0
err:     binding 2 : binding 6, stride 16, rate 1, divisor 1
err:     attr 3 : location 4, binding 0, format VK_FORMAT_R16G16_SFLOAT, offset 4
err:     binding 0 : binding 0, stride 8, rate 0, divisor 0
err:     binding 1 : binding 1, stride 20, rate 0, divisor 0
err:   DxvkGraphicsPipeline: Failed to compile pipeline
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Fragment shader function could not be compiled into pipeline. See previous logged error.
err:   DxvkGraphicsPipeline: Failed to compile pipeline
err:     vs  : VS_b3a78df1aff49f1edc7802a34a65c8c3ff8214f1
err:     fs  : FS_11085878e38b5fd3d0063f85611ac227e314dbaf
err:   DxvkGraphicsPipeline: Failed to compile pipeline
err:     vs  : VS_88e569163ccbf8a2152c8d9364efac1602531f82
err:     fs  : FS_32e42f016e1644d98fff8a0da2c737dd3daf7220
err:     attr 0 : location 3, binding 0, format VK_FORMAT_R32G32B32_SFLOAT, offset 0
err:     attr 6 : location 5, binding 4, format VK_FORMAT_R32G32B32A32_SFLOAT, offset 64
err:     attr 7 : location 4, binding 6, format VK_FORMAT_R32G32B32A32_SFLOAT, offset 0
err:   DxvkGraphicsPipeline: Failed to compile pipeline
err:     vs  : VS_88e569163ccbf8a2152c8d9364efac1602531f82
err:     fs  : FS_32e42f016e1644d98fff8a0da2c737dd3daf7220
err:     attr 0 : location 3, binding 0, format VK_FORMAT_R32G32B32_SFLOAT, offset 0
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Fragment shader function could not be compiled into pipeline. See previous logged error.
err:     attr 7 : location 5, binding 4, format VK_FORMAT_R32G32B32A32_SFLOAT, offset 64
err:     binding 0 : binding 0, stride 32, rate 0, divisor 0
err:     attr 2 : location 4, binding 0, format VK_FORMAT_R8G8B8A8_UNORM, offset 20
Process exited with code 0
```
```


### What version of Whisky are you using?

1.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by tarasis** [comment]
(I updated to 1.3.2 to verify that it still happened on that version)

**Comment by IsaacMarovitz** [comment]
Just made changes upstream that should resolve this

**Comment by tarasis** [comment]
Wonderful, thank you.

**Comment by brunocastello** [comment]
I am still having that issue with latest release.

My bottles are in an external SSD and I tend to go back and forth between two macs, both running Whisky, a M1 MBA and a M1 Max Studio.
