### ISSUE TITLE
[Bug]: Retina switch not available after install

### ISSUE THREAD

**Issue by kadorito** [Whisky-App/Whisky#435]
### Description

I just installed whisky on 2 different sonoma computers, and every time, I'm getting N/A for the retina switch config.

### Steps to reproduce

Install whisky, create bottle, go to config

### Expected behaviour

Retina switch should be present on a retina computer

### Logs

```bash
Don't know where to get the logs really
```

### What version of Whisky are you using?

2.0.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by kadorito** [comment]
<img width="547" alt="Capture d’écran 2023-09-26 à 22 31 02" src="https://github.com/Whisky-App/Whisky/assets/31277342/c90bb964-3413-4274-825c-7d59da799cfc">

**Comment by kadorito** [comment]
Workaround is to create the key manually, which makes teh switch pretty not useful

**Comment by DeerSteak** [comment]
Probably going to need to talk more about your configuration. This is what I see on a 14" MacBook Pro with M2 Pro running the public release of Sonoma. 

<img width="1229" alt="Screenshot 2023-09-26 at 9 05 34 PM" src="https://github.com/Whisky-App/Whisky/assets/991752/dbff5eac-a1e4-4d44-8224-c551818c7f25">

**Comment by kadorito** [comment]
Mac studio with studio display

**Comment by kadorito** [comment]
I'm not a swift specialist, but what I see in the code is that on first call, if the registry call returns "", then changeRetinaMode is called to add the key, but it does not create the "folder". Maybe it's the reason why ? (file is Wine.swift)

Also a quick fix : in SettingItemView(title: "config.retinaMode", loadingState: $retinaModeLoadingState)  (file is ConfigView.swift), the error message is wrong.

I would love to contribute a bit, at least help budfixing. The best IDE to fork the project is Xcode ?

**Comment by alex-skamander** [comment]
Hi, maybe a little late, but I found a solution to the problem by editing the registry. You need to create a new partition "Mac Driver" in "[HKEY_CURRENT_USER\Software\Wine\" and enter the parameter "RetinaMode" = "y" in it, then the switch will appear.
<img width="751" alt="red" src="https://github.com/Whisky-App/Whisky/assets/71153622/372cff42-9de5-4ecf-8ce0-d3389f10a83c"> 
<img width="381" alt="reg2" src="https://github.com/Whisky-App/Whisky/assets/71153622/4da4d883-dcaa-4c7c-b185-334ad46d9bb6">

**Comment by kadorito** [comment]
I know, this is what I did and as I mentioned earlier I believe this is the root cause.

**Comment by alex-skamander** [comment]
But now we have at least two ways to solve the problem)

**Comment by kadorito** [comment]
I already mentioned this workaround when posting the issue, but it's just making manually what the switch is supposed to to, it's not solving anything

**Comment by alex-skamander** [comment]
At least it solved my problem: the quality of the game became better, because I managed to remove the switch from being blocked. Isn't that the main thing?

**Comment by kadorito** [comment]
Of course but it's not the topic of the bug, as it's known knowledge that the switch is just setting this registry value.

**Comment by IsaacMarovitz** [comment]
Should be fixed

**Comment by kolyneh** [comment]
Still the same issue on 2.0.2.

```
Whisky Version: 2.0.2
Date: 2023/10/8 14:15:37
macOS Version: 版本14.0（版号23A344）
Bottle Name: Windows 10
Wine Version: 7.7.0
Windows Version: win10
Bottle URL: /Users/kolyneh/Library/Containers/com.isaacmarovitz.Whisky/Bottles/6B1D5B09-1840-4D2D-9EE3-BC50D5B44E15

Arguments: reg query HKCU\Software\Wine\Mac Driver -v RetinaMode 

Launched Wine (25201)
reg: �Ҳ�����ָ����ע�����
Process exited with code 1
```

Maybe it's because of the mojibake.
Run command `reg query "HKCU\Software\Wine\Mac Driver" -v RetinaMode` by cmd.exe then got:
```
reg: 找不到所指定的注册表项
```
It's localized and not match with the code here:
https://github.com/Whisky-App/Whisky/blob/2e132a1307330ce31d731b7fcf81f8c714b8ddeb/Whisky/Utils/Wine.swift#L231-L238

**Comment by IsaacMarovitz** [comment]
Hmm, I didn't know Wine would localise the error like that.

**Comment by IsaacMarovitz** [comment]
Pushed a fix

**Comment by kolyneh** [comment]
Great, thanks! I'll check after released.

**Comment by kolyneh** [comment]
Verified it has been fixed in version 2.1.0.
