### ISSUE TITLE
[Bug]: Created shortcut does not work

### ISSUE THREAD

**Issue by oguzhankrcb** [Whisky-App/Whisky#725]
### Description

I want to use WinSCP, it can be opened with normal run function, but when i create shortcut for it, it isn't starting the app.

### Steps to reproduce

1- Download WinSCP
2- Install it via Whisky
3- Run it then create shortcut
4- Close the app
5- Try to run it from shortcut

### Expected behaviour

I should be able to run from shortcut

### Logs

```bash
It can not be launched so there isn't any log.
```

### What version of Whisky are you using?

2.2.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by Ares-X** [comment]
same here

**Comment by hxhelm** [comment]
I have the same problem. I looked into the generated `launch` exectuable and the last parameter looks like it should be the executable, but the path to the bottle is used instead.

Changing the file contents of `/Applications/Warframe.app/Contents/MacOs/launch.sh` from

```sh
#!/bin/bash
DXVK_ASYNC=1 \
    WINEPREFIX=/Users/hxhelm/Library/Containers/com.isaacmarovitz.Whisky/Bottles/0AB98AF7-D544-4F4D-93E0-621419C8D18E \
    WINEMSYNC=1 \
    WINEDEBUG=fixme-all \
    /Users/hxhelm/Library/Application\ Support/com.isaacmarovitz.Whisky/Libraries/Wine/bin/wine64 \
    start /unix \
    /Users/hxhelm/Library/Containers/com.isaacmarovitz.Whisky/Bottles/0AB98AF7-D544-4F4D-93E0-621419C8D18E
```

to the actual executable like so:

```sh
#!/bin/bash
DXVK_ASYNC=1 \
    WINEPREFIX=/Users/hxhelm/Library/Containers/com.isaacmarovitz.Whisky/Bottles/0AB98AF7-D544-4F4D-93E0-621419C8D18E \
    WINEMSYNC=1 \
    WINEDEBUG=fixme-all \
    /Users/hxhelm/Library/Application\ Support/com.isaacmarovitz.Whisky/Libraries/Wine/bin/wine64 \
    start /unix \
    /Users/hxhelm/Library/Containers/com.isaacmarovitz.Whisky/Bottles/0AB98AF7-D544-4F4D-93E0-621419C8D18E/drive_c/users/crossover/AppData/Local/Warframe/Downloaded/Public/Tools/Launcher.exe
```

fixed it for me. (I added linebreaks for easier editing, you can ignore them if you want to try this fix.)

**Comment by oguzhankrcb** [comment]
@hxhelm it fixed the issue, thank you very much!

**Comment by IsaacMarovitz** [comment]
Should be resolved as of 2.2.4

**Comment by teunzwart** [comment]
This has mostly resolved non-functioning shortcuts, but whenever there is a space in the bottle path, there is still an error.

Example (non-functioning)

`#!/bin/bash
WINEPREFIX=/Users/teun/Games/Whisky/1DF4CF55-A1B4-411F-B599-8DDF71099B1E DXVK_ASYNC=1 WINEESYNC=1 WINEDEBUG=fixme-all WINEMSYNC=1 /Users/teun/Library/Application\ Support/com.isaacmarovitz.Whisky/Libraries/Wine/bin/wine64 start /unix /Users/teun/Games/Whisky/1DF4CF55-A1B4-411F-B599-8DDF71099B1E/drive_c/Steam/steamapps/common/Portal 2/portal2.exe`

Example (functioning [note the escaped space in the final path])

`#!/bin/bash
WINEPREFIX=/Users/teun/Games/Whisky/1DF4CF55-A1B4-411F-B599-8DDF71099B1E DXVK_ASYNC=1 WINEESYNC=1 WINEDEBUG=fixme-all WINEMSYNC=1 /Users/teun/Library/Application\ Support/com.isaacmarovitz.Whisky/Libraries/Wine/bin/wine64 start /unix /Users/teun/Games/Whisky/1DF4CF55-A1B4-411F-B599-8DDF71099B1E/drive_c/Steam/steamapps/common/Portal\ 2/portal2.exe`

**Comment by IsaacMarovitz** [comment]
Oversight again, latest commit should fix it.
