### ISSUE TITLE
[Bug]: BeamNG is broken by whisky v2.3.0

### ISSUE THREAD

**Issue by hw2007** [Whisky-App/Whisky#923]
### Description

After updating to Whisky 2.3.0, and installing "WhiskyWine", BeamNG.drive no longer works. It brings up a wine error saying the app needed to close, and then brings up an error from beamng saying that an error occurred in the user interface.
![Wine Error](https://github.com/Whisky-App/Whisky/assets/60082961/a704e7a2-a713-4a0b-a588-a84403d064b3)
<img width="301" alt="BeamNG Error" src="https://github.com/Whisky-App/Whisky/assets/60082961/599e979f-b864-4594-9269-4f987e4a35ac">

Also, is it possible to change the install location for whiskywine, so that I can use two versions of whisky at once (older one for beamng, newer one for everything else) until this gets fixed?

### Steps to reproduce

1. Install whisky 2.3.0 or higher
2. Install BeamNG.drive to a new windows 10 bottle with DXVK on (beamng needs this to run)
3. Try to run BeamNG

### Expected behaviour

The game should start without issues like it does in previous versions of whisky.

### Logs

```bash
Whisky Version: 2.3.1
Date: 2024-04-12T02:55:14Z
macOS Version: 14.4.1

Bottle Name: Beamng.drive
Bottle URL: /Users/braden/Library/Containers/com.isaacmarovitz.Whisky/Bottles/60104E4D-B1B2-4CCA-95F2-056B36178649

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

DXVK: true
DXVK Async: true
DXVK HUD: off

Arguments: start /unix /Users/braden/Library/Containers/com.isaacmarovitz.Whisky/Bottles/60104E4D-B1B2-4CCA-95F2-056B36178649/drive_c/Program Files (x86)/Steam/steamapps/common/BeamNG.drive/Bin64/BeamNG.drive.x64.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    "GST_DEBUG" = 1;
    WINEDEBUG = "fixme-all";
    WINEDLLOVERRIDES = "dxgi,d3d9,d3d10core,d3d11=n,b";
    WINEESYNC = 1;
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/braden/Library/Containers/com.isaacmarovitz.Whisky/Bottles/60104E4D-B1B2-4CCA-95F2-056B36178649";
}

msync: bootstrapped mach port on wine-3a2c266-msync.
msync: up and running.
0100:err:setupapi:SetupDefaultQueueCallbackW copy error 1812 L"@C:\\windows\\system32\\drivers\\wineusb.sys,-1" -> L"C:\\windows\\inf\\wineusb.inf"
wine: configuration in L"/Users/braden/Library/Containers/com.isaacmarovitz.Whisky/Bottles/60104E4D-B1B2-4CCA-95F2-056B36178649" has been updated.
info:    VK_KHR_surface
info:    Memory Heap[0]: 
info:    VK_KHR_win32_surface
info:      Size: 16384 MiB
info:    Buffer size:  1800x1019
```

### What version of Whisky are you using?

2.3.1

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by killsecurly** [comment]
A `TS_PROCESS_CRASHED` Segmentation Fault is usually when an antivirus of some sort is blocking the item required to run, such as in this case, `MainGEUI`. Or, the app does not have the system permissions to access the folder with `MainGUEI` in it. Try disabling antiviruses and allow all users to View & Edit in Finder.

Another thing to try might be verifying game files integrity on Steam. (If you are using it)

**Comment by hw2007** [comment]
> A `TS_PROCESS_CRASHED` Segmentation Fault is usually when an antivirus of some sort is blocking the item required to run, such as in this case, `MainGEUI`. Or, the app does not have the system permissions to access the folder with `MainGUEI` in it. Try disabling antiviruses and allow all users to View & Edit in Finder.
> 
> Another thing to try might be verifying game files integrity on Steam. (If you are using it)

I have already verified game files, also tried reinstalling the game completely. As for antivirus stuff, I do not have any antivirus software installed to my mac (besides whatever apple includes). I decided to try setting the entire bottle to view & edit for everyone, but that didn't do anything.

**Comment by thepolarbear0818** [comment]
I have the exact same issues. Same errors, same issues. Is there a way to roll back to a previous version so that I can play BeamNG again?

**Comment by hw2007** [comment]
> I have the exact same issues. Same errors, same issues. Is there a way to roll back to a previous version so that I can play BeamNG again?

Yes, you can! 

1. Download any version before update 2.3.0 from the [releases page](https://github.com/Whisky-App/Whisky/releases)
2. Open the whisky version you just downloaded
3. In the menu bar, hit Whisky >> Setup...
4. Hit "Uninstall" on GPTK
5. Hit "Next", and it will start installing the old version of GPTK which doesn't have this bug.

Note: You will not be able to use newer versions of whisky unless you install the new WhiskyWine, which will make beamng stop working again.

**Comment by deepdarkenergy** [comment]
same issue here, wish it could be fixed soon

**Comment by CatsoftwareOfficial** [comment]
Same problem, hope it will be fixed soon

**Comment by Another2846** [comment]
Another week I hope it will get fixed

**Comment by 8Bitz0** [comment]
Have any other programs using CEF been having issues? Steam seems to have no problem despite its heavy reliance on CEF.

**Comment by hw2007** [comment]
> Have any other programs using CEF been having issues? Steam seems to have no problem despite its heavy reliance on CEF.

Could you please tell me what CEF means?
None of the other programs I have had any issues, only BeamNG.

**Comment by 8Bitz0** [comment]
> > Have any other programs using CEF been having issues? Steam seems to have no problem despite its heavy reliance on CEF.
> 
> Could you please tell me what CEF means? None of the other programs I have had any issues, only BeamNG.

CEF is the Chromium Embedded Framework, which basically allows using Chromium web views within your graphical application. BeamNG.drive uses this for the user interface. Chromium has a history of breaking inside Wine. I was wondering if other applications using CEF or even Electron-based (which uses Chromium to create the interface for the entire application, like Discord) stopped working.

Have you tried running an older version of the game from the Steam betas menu for BeamNG?

**Comment by jacobtohahn** [comment]
This happens on my Mac with an M1 Max. I created a new bottle with a fresh install of Steam and BeamNG, using Whisky 2.3.2. 
<img width="442" alt="Screenshot 2024-05-21 at 9 43 17 PM" src="https://github.com/Whisky-App/Whisky/assets/25017830/f145f18e-700a-4f02-af44-490869f3bed0">

**Comment by hw2007** [comment]
> This happens on my Mac with an M1 Max. I created a new bottle with a fresh install of Steam and BeamNG, using Whisky 2.3.2. <img alt="Screenshot 2024-05-21 at 9 43 17 PM" width="442" src="https://private-user-images.githubusercontent.com/25017830/332627550-f145f18e-700a-4f02-af44-490869f3bed0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNDI3MTIsIm5iZiI6MTcxNjM0MjQxMiwicGF0aCI6Ii8yNTAxNzgzMC8zMzI2Mjc1NTAtZjE0NWYxOGUtNzAwYS00ZjAyLWFmNDQtNDkwODY5ZjNiZWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDAxNDY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMzczMmE3OTg5ZWZkNTdmZTQ1ZmYwNTgzYzAzNDU5YjAzZjQzMGM0YTA0Mzg5OTYzOGNiZjc0ZmMxMTkyZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Iokh4SNIbTwt8AGpzJsoWNfsZyyYGhi1BvjvUFFnXQU">

When swapping to older versions of Whisky, you need to reinstall GPTK otherwise it will still use the new one.

1. In the menu bar, hit Whisky >> Setup...
2. Hit "Uninstall" on GPTK.
3. Hit "Next", and it will start installing the old version of GPTK.

**Comment by hw2007** [comment]
> > > Have any other programs using CEF been having issues? Steam seems to have no problem despite its heavy reliance on CEF.
> 
> > 
> 
> > Could you please tell me what CEF means? None of the other programs I have had any issues, only BeamNG.
> 
> 
> 
> CEF is the Chromium Embedded Framework, which basically allows using Chromium web views within your graphical application. BeamNG.drive uses this for the user interface. Chromium has a history of breaking inside Wine. I was wondering if other applications using CEF or even Electron-based (which uses Chromium to create the interface for the entire application, like Discord) stopped working.
> 
> 
> 
> Have you tried running an older version of the game from the Steam betas menu for BeamNG?

Ah, okay. No I have not tried installing an older version.

**Comment by arctorin** [comment]
Is there an update to this issue? I am getting the same issue described here as well.

**Comment by Ezekielman** [comment]
Same here. I just bought the game, I'm sad that I can't play it.

**Comment by hw2007** [comment]
> Same here. I just bought the game, I'm sad that I can't play it.

You can still play it, you just need to install an older version of whisky!

See my instructions here >> https://github.com/Whisky-App/Whisky/issues/923#issuecomment-2054283802

**Comment by cmartell-at-ocp** [comment]
Can confirm this is an issue in other games as well. UE5.4 project stops working with 2.3.0 and newer. Downgraded to 2.2.4 and game is working again.

**Comment by killsecurly** [comment]
> Can confirm this is an issue in other games as well. UE5.4 project stops working with 2.3.0 and newer. Downgraded to 2.2.4 and game is working again.

@cmartell-at-ocp 

I feel like Whisky2 just has a problem in general.

**Comment by IsaacMarovitz** [comment]
Fixed in WhiskyWine 2.4.1

**Comment by Ezekielman** [comment]
Tested on Whisky 2.3.2 with the latest version of WhiskyWine. Tested on Windows 10, and 11, with and without DXVK, and with and without MSync. Still no workie.
![Screenshot 2024-09-18 at 19 42 26](https://github.com/user-attachments/assets/5c640e9a-85de-4b7d-a520-e2a9e4859650)
![Screenshot 2024-09-18 at 19 42 34](https://github.com/user-attachments/assets/ebf274f3-efcf-4eb0-8b45-551f3022ea9a)

**Comment by hw2007** [comment]
Can confirm, this issue is NOT resolved. Still broken for me as well. @IsaacMarovitz

**Comment by IsaacMarovitz** [comment]
It took a few hours for the WhiskyWine update to propagate, make sure you're up to date and you completely restart everything on the new Wine version.

**Comment by hw2007** [comment]
> It took a few hours for the WhiskyWine update to propagate, make sure you're up to date and you completely restart everything on the new Wine version.

Yup, confirming that now that the update appeared it is resolved. Yippee!
